server:
  port: ${SERVER_PORT}
#  ssl:
#    protocol: TLS
#    enabled-protocols:
#      - TLSv1.2
#    enabled: true
#    key-store-type: PKCS12
#    key-store: classpath:tls/keystore.p12
#    key-store-password: changeit
cloud:
  aws:
    stack: false
    stack.auto: false
    region:
      static: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
logging:
  level:
    ROOT: INFO
    com.soul.core: DEBUG
    org.springframework: INFO
    org.mongodb: ERROR
    com.amazonaws.util.EC2MetadataUtils: ERROR
spring:
  data:
    mongodb:
      uri: ${DB_URI}
      database: ${DB_NAME}
  jackson:
    default-property-inclusion: non_null
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: true
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: [ 'configprops', 'env', 'health', 'info', 'jhimetrics', 'logfile', 'loggers', 'prometheus', 'threaddump', 'caches' ]
application:
  aws:
    menuBucketPrefix: "soul-menu"
  security:
    authentication:
      secret: ${APPLICATION_SECURITY_AUTHENTICATION_SECRET}
      validity-sec: 3600
      validity-remember-me-sec: 7200
    cors:
      allowed-origin-patterns: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
    content-security-policy: "default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:"